version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SelfLearningDb
  dev-auth:
    image: ghcr.io/e-learning-by-sse/infrastructure-fake-oidc
    ports:
      - 8090:8090

